dns_domain: gsb.local
netbios_name: GSB
admin_password: Formation13@
admin_pass: Formation13@

# Compte de service GLPI pour LDAP
glpi_ldap_password: "Formation13@"
nextcloud_ldap_password: "Formation13@"
mail_ldap_password: "Formation13@"
sftpgo_ldap_password: "Formation13@"

# Nextcloud
nextcloud_container_name: "nextcloud"
nextcloud_admin_user: "nextcloud"
nextcloud_admin_password: "Formation13@"
nextcloud_port: 8080

# Nextcloud LDAP
nextcloud_ldap_host: "172.16.0.1"
nextcloud_ldap_port: "389"
nextcloud_ldap_base_dn: "DC=gsb,DC=local"
nextcloud_ldap_bind_dn: "CN=nextcloud_bind,OU=Comptes_Services,DC=gsb,DC=local"
nextcloud_ldap_bind_password: "Formation13@"
nextcloud_ldap_user_filter: "(&(objectClass=user)(objectCategory=person))"
nextcloud_ldap_login_filter: "(&(objectClass=user)(objectCategory=person)(sAMAccountName=%uid))"
nextcloud_ldap_group_filter: "(&(objectClass=group))"
nextcloud_ldap_user_display_name: "displayName"
nextcloud_ldap_group_display_name: "cn"