#SPDX-License-Identifier: MIT-0
---
# defaults file for roles/Nextcloud

# Nextcloud Configuration
nextcloud_version: "30"
nextcloud_container_name: "nextcloud"
nextcloud_port: 8080

# Database Configuration
nextcloud_db_type: "mysql"
nextcloud_db_container_name: "nextcloud-db"
mariadb_version: "11.2"
nextcloud_db_name: "nextcloud"
nextcloud_db_user: "nextcloud"
nextcloud_db_password: "Nextcloud_DB_Passw0rd!"
nextcloud_db_root_password: "Nextcloud_Root_Passw0rd!"

# Redis Configuration
nextcloud_redis_container_name: "nextcloud-redis"
redis_version: "7-alpine"

# Admin Configuration
nextcloud_admin_user: "nextcloud"
nextcloud_admin_password: "Formation13@"

# LDAP Configuration
nextcloud_ldap_enabled: true
nextcloud_ldap_host: "172.16.0.1"
nextcloud_ldap_port: "389"
nextcloud_ldap_base_dn: "DC=gsb,DC=local"
nextcloud_ldap_bind_dn: "CN=nextcloud_bind,OU=Comptes_Services,DC=gsb,DC=local"
nextcloud_ldap_bind_password: "{{ nextcloud_ldap_password | default('Formation13@') }}"
nextcloud_ldap_user_filter: "(&(objectClass=user)(objectCategory=person))"
nextcloud_ldap_login_filter: "(&(objectClass=user)(objectCategory=person)(sAMAccountName=%uid))"
nextcloud_ldap_group_filter: "(&(objectClass=group))"
nextcloud_ldap_user_display_name: "displayName"
nextcloud_ldap_group_display_name: "cn"

# Domain
nextcloud_domain: "gsb.local"

# Trusted Domains
nextcloud_trusted_domains:
  - "172.16.69.3"
  - "172.16.0.254"
  - "nextcloud.gsb.local"
  - "192.168.50.81"
