ou_name: "Mugiwara"
group_name: "mugiwaras"
ou_path: "DC=gsb,DC=local"
folder_name: "Thousand_Sunny"
drive_letter: "D"
block_cmd: "non"
block_control_panel: "oui"

vlan_id: 47
vlan_name: "OnePiece"

id_vif: "47"
ip_vif: "192.168.47.254/24"
dhcp_start: "192.168.47.100"
dhcp_stop: "192.168.47.200"
dhcp_gateway: "192.168.47.254"
dhcp_dns: "172.16.0.3"

firewall_rule: "oui"
vlan_source: "47"
vlan_dest: "300"
service: "ssh"
description: "cnjsoced"

nat_rule: "non"

create_nextcloud_folder: "oui"
nextcloud_folder_name: "Mugiwaras"

users:
  - firstname: "Luffy"
    lastname: "Monkey"
    username: "Monkey D. Luffy"
    password: "Formation13@"
    email: "monkey.d.luffy@gsb.local"

domains:
  - "goldroger.com"

switch_ports:
  Sw01:
    access_ports:
      []
    trunk_ports:
      - "lag1"
      - "gi5"
      - "gi6"
  Sw02:
    access_ports:
      - "gi6"
    trunk_ports:
      - "lag1"
