ou_name: "Les_tigres"
group_name: "grp_les_tigres"
ou_path: "DC=gsb,DC=local"
folder_name: "les_tigres"
drive_letter: "T"
block_cmd: "oui"
block_control_panel: "non"

vlan_id: 89
vlan_name: "Les_tigres"

id_vif: "89"
ip_vif: "192.168.89.254/24"
dhcp_start: "192.168.89.10"
dhcp_stop: "192.168.89.200"
dhcp_gateway: "192.168.89.254"
dhcp_dns: "172.16.0.3"

firewall_rule: "oui"
vlan_source: "89"
vlan_dest: "300"
service: "ssh"
description: "Block ssh sur 300"

nat_rule: "non"

create_nextcloud_folder: "oui"
nextcloud_folder_name: "Les_Tigres"

users:
  - firstname: "leq"
    lastname: "letigre"
    username: "LeQ Letigre"
    password: "Formation13@"
    email: "leq.letigre@gsb.local"
  - firstname: "nonow"
    lastname: "letigre"
    username: "hudie"
    password: "Formation13@"
    email: "nono@gsb.local"

domains:
  - "pornhub.fr"
  - "facebook.com"

switch_ports:
  Sw01:
    access_ports: []
    trunk_ports:
      - "lag1"
      - "gi5"
      - "gi6"
  Sw02:
    access_ports:
      - "gi6"
    trunk_ports:
      - "lag1"
